# coding: utf-8

"""
    ECE 461 - Fall 2021 - Project 2

    API for ECE 461/Fall 2021/Project 2: A Trustworthy Module Registry  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: davisjam@purdue.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PackageQuery(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'version': 'SemverRange',
        'name': 'PackageName'
    }

    attribute_map = {
        'version': 'Version',
        'name': 'Name'
    }

    def __init__(self, version=None, name=None):  # noqa: E501
        """PackageQuery - a model defined in Swagger"""  # noqa: E501
        self._version = None
        self._name = None
        self.discriminator = None
        if version is not None:
            self.version = version
        self.name = name

    @property
    def version(self):
        """Gets the version of this PackageQuery.  # noqa: E501


        :return: The version of this PackageQuery.  # noqa: E501
        :rtype: SemverRange
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this PackageQuery.


        :param version: The version of this PackageQuery.  # noqa: E501
        :type: SemverRange
        """

        self._version = version

    @property
    def name(self):
        """Gets the name of this PackageQuery.  # noqa: E501


        :return: The name of this PackageQuery.  # noqa: E501
        :rtype: PackageName
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PackageQuery.


        :param name: The name of this PackageQuery.  # noqa: E501
        :type: PackageName
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PackageQuery, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PackageQuery):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
