# coding: utf-8

"""
    ECE 461 - Fall 2021 - Project 2

    API for ECE 461/Fall 2021/Project 2: A Trustworthy Module Registry  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: davisjam@purdue.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.user_authentication_info import UserAuthenticationInfo  # noqa: E501
from swagger_client.rest import ApiException


class TestUserAuthenticationInfo(unittest.TestCase):
    """UserAuthenticationInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserAuthenticationInfo(self):
        """Test UserAuthenticationInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.user_authentication_info.UserAuthenticationInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
