# coding: utf-8

"""
    ECE 461 - Fall 2021 - Project 2

    API for ECE 461/Fall 2021/Project 2: A Trustworthy Module Registry  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: davisjam@purdue.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_auth_token(self):
        """Test case for create_auth_token

        """
        pass

    def test_package_by_name_delete(self):
        """Test case for package_by_name_delete

        Delete all versions of this package.  # noqa: E501
        """
        pass

    def test_package_by_name_get(self):
        """Test case for package_by_name_get

        """
        pass

    def test_package_create(self):
        """Test case for package_create

        """
        pass

    def test_package_delete(self):
        """Test case for package_delete

        Delete this version of the package.  # noqa: E501
        """
        pass

    def test_package_rate(self):
        """Test case for package_rate

        """
        pass

    def test_package_retrieve(self):
        """Test case for package_retrieve

        """
        pass

    def test_package_update(self):
        """Test case for package_update

        Update this version of the package.  # noqa: E501
        """
        pass

    def test_packages_list(self):
        """Test case for packages_list

        Get packages  # noqa: E501
        """
        pass

    def test_registry_reset(self):
        """Test case for registry_reset

        """
        pass


if __name__ == '__main__':
    unittest.main()
